### ISSUE TITLE
Разделение логики и отображения

### ISSUE THREAD

**Issue by coursar** [Targonkp/Homework2#4]
https://github.com/Targonkp/Homework2/blob/301f1fc9d518dc1eb2772dd75b1c6d142d27a0c0/src/js/rolls.js#L6-L12

**Comment by coursar** [comment]
Вы должны в одной функции считать, а вывод организовывать в другом месте (см. лекции).

**Comment by Targonkp** [comment]
Понятно, поэтому автотест не запускается и останавливается на событии (addevent)?

**Comment by coursar** [comment]
Авто-тесты пока ничего не знают про DOM.
